function ECMAScript_unified_tokens(){
 var r=[],x=
 // from PEGinfo()'s list of missing dependencies:
 ["FalseTok"
 ,"TrueTok"
 ,"NullTok"
 ,"BreakTok"
 ,"ContinueTok"
 ,"DebuggerTok"
 ,"InTok"
 ,"ElseTok"
 ,"InstanceOfTok"
 ,"DeleteTok"
 ,"FunctionTok"
 ,"NewTok"
 ,"ThisTok"
 ,"TypeofTok"
 ,"VoidTok"
 ,"IfTok"
 ,"DoTok"
 ,"WhileTok"
 ,"ForTok"
 ,"VarTok"
 ,"ReturnTok"
 ,"CaseTok"
 ,"DefaultTok"
 ,"SwitchTok"
 ,"ThrowTok"
 ,"CatchTok"
 ,"FinallyTok"
 ,"TryTok"
 ,"EqTok"
 ,"WithTok"].forEach(function(x){
  r.push(x+' ← "'+x.slice(0,-3).toLowerCase()+'" !(IdentifierPart)')})
 return r.join('\n')}